datalist_hy = [

# food
{'kind': 'food', 'category': 'Pizza', 'name': 'Պիցա Պեպերոնի', 'quantity': '1 կտոր', 'price': 450, 'description': 'Պեպերոնի պիցցան դասական նախընտրելի ընտրություն է՝ հարուստ և կծու համով։ Այն պատրաստված է փափուկ թխված խմորով, որի վրա դրված է լոլիկի սոուս, հալված մոցարելլա պանիր և պեպերոնիի կծու կտորներ։ Ամեն կծում հարստացած է իտալական համեմունքներով՝ օրեգանո և ռեհան։ Վերջում ավելացվում է մի փոքր ձիթայուղ՝ պիցցային տալով թեթև խրթխրթանություն և բույր։', 'image': 'test_pizza_pepperoni.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Pizza', 'name': 'Պիցա Մարգարիտա', 'quantity': '1 կտոր', 'price': 300, 'description': 'Պիցցա Մարգարիտան պարզ, բայց համեղ դասական է։ Այն պատրաստված է նուրբ, խրթխրթան խմորով, որի վրա դրված է թարմ լոլիկի սոուս, կրեմային մոցարելլա պանիր և կծու բազիլիկի տերևներ։ Պիցցան ավարտվում է մի փոքր ձիթայուղով, որը համահունչ դարձնում է բաղադրիչների թարմ, թեթև և հարմարավետ համը։ Դա կատարյալ ընտրություն է նրանց համար, ովքեր գնահատում են ավանդական իտալական համը։', 'image': 'test_pizza_margarita.webp', 'language': 'hy'},
{"kind": "food", "category": "Pizza", "name": "Պիցա Կապրիչոզա", "quantity": "1 կտոր", "price": 650, "description": "Պիցա Կապրիչիոզան համեղ և դոզված ընտրություն է պիցցայի սիրահարների համար։ Այն պատրաստված է խրթխրթան խմորով, որը քած է հարուստ լոլիկի սոուսով, կրեմային մոցարելլայով, համեղ խոզապուխտով, սնկով և արթիչոկներով։ Պիցցան ավարտվում է օղակներով օղիների և մի փոքր ձիթայուղի շաղ տալով, ինչը նրան տալիս է համամասնված համադրություն աղի և թթու համերի։ Դա կատարյալ ընտրություն է նրանց համար, ովքեր սիրում են մի խորտիկի մեջ տարբեր տեքստուրներ և համեր։", "image": "test_pizza_capricciosa.webp", "language": "hy"},
{'kind': 'food', 'category': 'Pizza', 'name': 'Պիցա Սնկով', 'quantity': '1 կտոր', 'price': 500, 'description': 'Պիցա Սնկովը հիանալի ընտրություն է սնկի սիրահարների համար։ Պիցցան ծածկված է հարուստ լոլիկի սոուսով, կրեմային մոցարելլայով և առատ քանակությամբ թարմ սնկերով։ Սնկերի հողի համը համադրում է կրեմային պանիրն ու համեղ սոուսը, ստեղծելով կատարյալ տեքստուրայի և համի հավասարակշռություն։ Այս պիցցան կատարյալ է նրանց համար, ովքեր սիրում են սնկի խորը համը խրթխրթան խմորում։', 'image': 'test_pizza_mushroom.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Pizza', 'name': 'Պիցա Ծովամթերքով', 'quantity': '1 կտոր', 'price': 700, 'description': 'Պիցա Ծովամթերքովը կատարյալ ընտրություն է ծովամթերքի սիրահարների համար։ Այս պիցցան պարունակում է հրաշալի համակցություն սառցագործներից, խեցգետիններից և ծովախեցգետիններից, ծածկված հարուստ լոլիկի սոուսով և հալված մոցարելլայով։ Ծովամթերքի համն ու կրեմային պանիրը միանգամայն հիանալի համադրվում են, ստեղծելով համերի կատարյալ համընթացություն։ Փորձեք օվկիանոսի համը յուրաքանչյուր կտորով այս համեղ պիցցայից։', 'image': 'test_pizza_seafood.webp', 'language': 'hy'},

{'kind': 'food', 'category': 'Soup', 'name': 'Լոլիկի ապուր', 'quantity': '1 ափսե', 'price': 1800, 'description': 'Լոլիկի ապուրը հարմարավետ դասական է, որը հիանալի է ցանկացած սեզոնի համար։ Այս հարուստ և կրեմային ապուրը պատրաստվում է թարմ լոլիկներից, որոնք դանդաղ եփվում են համեմունքների և բուսաբառերի հետ։ Մեղմ տեքստուրան և համեղ համը կտեղավորեն ձեզ ներսից դուրս։ Վայելեք այս տնային ապուրի համերը, իսկապես համտեսեք ձեր համային զգացողությունները։', 'image': 'test_tomato_soup.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Soup', 'name': 'Հավի լապշայի ապուր', 'quantity': '1 ափսե', 'price': 2400, 'description': 'Հավի լապշայի ապուրը համեղ և նուրացնող ճաշատեսակ է, պատրաստված նուրբ հավի կտորներով, համեղ բուլյոնով և փափուկ լապշայով։ Թարմ բանջարեղենների և բուրավետ համեմունքների համադրությունը ստեղծում է կոմֆորտային և սննդարար ապուր։ Այս ապուրը հիանալի է ցանկացած սեզոնի համար, այն կսպասարկի ձեր համը և կսահմանափակի ձեր ախորժակը իր համով։', 'image': 'test_chicken_noodle_soup.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Soup', 'name': 'Բրոկկոլիի և չեդարի ապուր', 'quantity': '1 ափսե', 'price': 2200, 'description': 'Բրոկկոլիի և չեդարի ապուրը կրեմային և համեղ ապուր է, պատրաստված թարմ բրոկկոլի և լոբարված չեդար պանրի հետ։ Բաղադրիչների հարուստ և հարթ տեքստուրան համադրված բրոկկոլիի երկրի համի և չեդարի խառը համով դարձնում է այս ապուրը ոչ միայն հարմարավետ, այլև հագեցնող։ Հիանալի է կոմֆորտային ճաշի համար, այն կտա տաք և համեղ փորձ։', 'image': 'test_borccoli_cheddar_soup.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Soup', 'name': 'Մացո գնդիկներով ապուր', 'quantity': '1 ափսե', 'price': 2500, 'description': 'Մացո գնդիկներով ապուրը հարմարավետ և համեղ ապուր է, պատրաստված թեթև և փափուկ մացո գնդիկներով, որոնք մատուցվում են համեղ հնդկացորենի բուլյոնում։ Մացո գնդիկները, պատրաստված մացո ալյուրից, ձվերից և համեմունքներից, ունեն բավարարող տեքստուրա, մինչդեռ հարուստ բուլյոնն ավելացնում է տաքություն և խորություն այս ճաշատեսակին։ Կլասիկ եբրայերեն հարմարավետ սնունդ, որը հիանալի է ցանկացած առիթի համար։', 'image': 'test_matzo_ball_soup.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Soup', 'name': 'Ֆո ապուր', 'quantity': '1 ափսե', 'price': 2100, 'description': 'Ֆո ապուրը վիետնամական ավանդական ուտեստ է, որը ներառում է համեղ և հոտավետ բուլյոն, պատրաստված եռացող գառան ոսկորներից, խոտաբույսերից և համեմունքներից։ Այն ներառում է բրինձի լապշա, նուրբ կտրված գառ, և թարմ խոտաբույսեր՝ համեղ և համեմունքային համային պրոֆիլով։ Հիանալի ընտրություն է տաք, սիրված ուտեստի համար, որը միաժամանակ հանգստացնում և հագեցնում է համը։', 'image': 'test_pho_soup.avif', 'language': 'hy'},

{'kind': 'food', 'category': 'Barbecue', 'name': 'Խոզի կողեր', 'quantity': '1 բաժին', 'price': 3200, 'description': 'Բարեկենդի խոզի կողերը՝ փափուկ և հյութալի, դանդաղ պատրաստված՝ կատարյալ արդյունքով և հարուստ ծխոտ համով։ Կողերը պատված են հատուկ համեմունքների և խորոված սոուսով՝ համեղ համային շերտերով՝ աղի, քաղցր և ծխոտ նշաններով։ Անհրաժեշտ ուտեստ է խորովածի սիրահարների համար։', 'image': 'test_porkribs_barbecue.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Կրծքամիս', 'quantity': '1 բաժին', 'price': 3200, 'description': 'Հյութալի և փափուկ կրծքամիս, դանդաղ պատրաստված՝ կատարյալ արդյունքով և ծխոտ համով։ Այն պատված է հատուկ համեմունքների և խորոված սոուսով՝ համեղ և հարուստ համով, որը հալվում է բերանում։ Պատասխան է խորովածի սիրահարների համար՝ պատրաստ լինելու համեղ և համեղ ուտեստից։', 'image': 'test_brisket_barbecue.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Ամբողջական խոզ', 'quantity': '1 բաժին', 'price': 130000, 'description': 'Մի ամբողջ խոզ, դանդաղ պատրաստված՝ կատարյալ արդյունքով և ծխոտ համով՝ հյութալի և փափուկ։ Այս հսկայական խորովածը պատված է համեմունքների հատուկ խառնուրդով և պատրաստված է դանդաղ, որպեսզի յուրաքանչյուր կուլտուրա լի լինի հարուստ ծխոտ համով։ Պատասխան է մեծ հավաքույթների կամ անմոռանալի տոնախմբություն ցանկացողների համար!', 'image': 'test_wholehog_barbecue.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Հավ', 'quantity': '1 բաժին', 'price': 2800, 'description': 'Փափուկ հավ, խորոված կատարված կատարյալ ծխոտ համով։ Այս խորոված հավը պատված է հատուկ համեմունքների խառնուրդով և պատրաստվում է դանդաղ՝ հասնելու համար հյութալիության և ծխոտության կատարյալ հավասարակշռությանը։ Մատչելի ընտրություն է խորոված սիրահարների համար!', 'image': 'test_chicken_barbecue.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Քյաբաբ', 'quantity': '1 բաժին', 'price': 1900, 'description': 'Համեղ և փափուկ խաշած միս՝ պատրաստված խորովածով, հատուկ համեմունքների խառնուրդով՝ աննկարագրելի խորովածի փորձառություն ստանալու համար։ Վառ խոհանոցում պատրաստված՝ բնական համերն առավելագույնս բացահայտելու համար և մատուցվում տաք՝ համեղ ուտեստի համար!', 'image': 'test_qabab_barbecue.webp', 'language': 'hy'},

{'kind': 'food', 'category': 'Burger', 'name': 'Չիզբուրգեր', 'quantity': '1 բաժին', 'price': 1800, 'description': 'Կլասիկ Չիզբուրգեր՝ հյութեղ գառան հորթի կոտլետ, հալեցված պանիր և թարմ բաղադրիչներ, մատուցվում է փափուկ հացով՝ հաճելի և համեղ ուտեստի համար։ Սկսած բուրգեր սիրահարների համար, որոնք գնահատում են համային հիանալի համադրությունը։', 'image': 'test_cheeseburger_burger.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Burger', 'name': 'Բեկոն բուրգեր', 'quantity': '1 բաժին', 'price': 2200, 'description': 'Համեղ Բեկոն բուրգեր՝ հյութեղ գառան հորթի կոտլետով, խրթխրթացող բեկոնով, հալեցված պանիրով և թարմ բաղադրիչներով, մատուցվում է փափուկ հացով՝ համեղ ուտեստի համար։ Լավագույն ընտրությունը բեկոնի սիրահարների համար, ովքեր գնահատում են հագեցած և համեղ համը։', 'image': 'test_baconburger_burger.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Burger', 'name': 'Հավի բուրգեր', 'quantity': '1 բաժին', 'price': 2000, 'description': 'Համեղ Հավ բուրգեր՝ նուրբ հավի կոտլետով, թարմ բանջարեղենով և փափուկ հացով, որը կտրամադրի բավարարում և հագեցած համ այն մարդկանց համար, ովքեր նախընտրում են հավը՝ գառան փոխարեն։ Հիանալի համ և տեքստուրայի համակցություն ցանկացած բուրգերի սիրահարների համար։', 'image': 'test_chickenburger_burger.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Burger', 'name': 'Նախաճաշի բուրգեր', 'quantity': '1 բաժին', 'price': 2400, 'description': 'Սկսեք ձեր օրը համեղ նախաճաշի բուրգերով, որը համադրում է ձվածեղ, բեկոն, պանիր և փափուկ հաց։ Այս հարուստ նախաճաշը կատարյալ է նրանց համար, ովքեր ցանկանում են լիարժեք և համեղ կերակուր՝ իրենց առավոտը սկսելու համար։', 'image': 'test_breakfastburger_burger.webp', 'language': 'hy'},
{'kind': 'food', 'category': 'Burger', 'name': 'Վեգան սլայդերներ', 'quantity': '1 բաժին', 'price': 2500, 'description': 'Նվաճեք բուսակերների համը այս վեգան սլայդերներով։ Ամեն սլայդեր համադրում է համեղ տապակած պատառիկ, թարմ բանջարեղեններ և փափուկ հաց՝ առաջարկելով համեղ և հագեցնող քերակուր՝ ինչպես բուսակերների, այնպես էլ ոչ բուսակերների համար։', 'image': 'test_sliders_burger.webp', 'language': 'hy'},


# drink
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Լոնգ Այլենդ', 'quantity': '1 բաժակ', 'price': 3400, 'description': 'Լոնգ Այլենդ, շատ լավ Լոնգ Այլենդ, հոյակապ Լոնգ Այլենդ', 'image': 'test_cocktail_longisland.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Բլադի Մարիա', 'quantity': '1 բաժակ', 'price': 4200, 'description': 'Բլադի Մարիա, շատ լավ Բլադի Մարիա, հոյակապ Բլադի Մարիա', 'image': 'test_bloodymaria_cocktail.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Մոխիտո', 'quantity': '1 բաժակ', 'price': 1800, 'description': 'Մոխիտո, շատ լավ Մոխիտո, հոյակապ Մոխիտո', 'image': 'test_mojito_cocktail.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Նեգրոնի', 'quantity': '1 բաժակ', 'price': 2200, 'description': 'Նեգրոնի, շատ լավ Նեգրոնի, հոյակապ Նեգրոնի', 'image': 'test_nogroni_cocktail.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Մանհեթեն', 'quantity': '1 բաժակ', 'price': 2800, 'description': 'Մանհեթեն, շատ լավ Մանհեթեն, հոյակապ Մանհեթեն', 'image': 'test_manhattan_cocktail.webp', 'language': 'hy'},

{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Coca-cola', 'quantity': '1 շիշ', 'price': 550, 'description': 'Coca-cola, շատ լավ Coca-cola, հոյակապ Coca-cola', 'image': 'test_sodadrink_cocacola.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Fanta', 'quantity': '1 շիշ', 'price': 550, 'description': 'Fanta, շատ լավ Fanta, հոյակապ Fanta', 'image': 'test_fanta_sodadrink.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Sprite', 'quantity': '1 շիշ', 'price': 550, 'description': 'Sprite, շատ լավ Sprite, հոյակապ Sprite', 'image': 'test_sprite_sodadrink.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Pepsi', 'quantity': '1 շիշ', 'price': 550, 'description': 'Pepsi, շատ լավ Pepsi, հոյակապ Pepsi', 'image': 'test_pepsi_sodadrink.avif', 'language': 'hy'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Mirinda', 'quantity': '1 շիշ', 'price': 550, 'description': 'Mirinda, շատ լավ Mirinda, հոյակապ Mirinda', 'image': 'test_mirinda_sodadrink.webp', 'language': 'hy'},

{'kind': 'drink', 'category': 'Vodka', 'name': 'Absolut', 'quantity': '1 շիշ', 'price': 13500, 'description': 'Absolut, շատ լավ Absolut, հոյակապ Absolut', 'image': 'test_vodka_absolut.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Finlandia', 'quantity': '1 շիշ', 'price': 9000, 'description': 'Finlandia, շատ լավ Finlandia, հոյակապ Finlandia', 'image': 'test_finlandia_vodka.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Russian Standard', 'quantity': '1 շիշ', 'price': 12000, 'description': 'Russian Standard, շատ լավ Russian Standard, հոյակապ Russian Standard', 'image': 'test_russianstandard_vodka.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Stolichnaya', 'quantity': '1 շիշ', 'price': 11500, 'description': 'Stolichnaya, շատ լավ Stolichnaya, հոյակապ Stolichnaya', 'image': 'test_stolichnaya_vodka.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'SKYY', 'quantity': '1 շիշ', 'price': 13000, 'description': 'SKYY, շատ լավ SKYY, հոյակապ SKYY', 'image': 'test_skyy_vodka.webp', 'language': 'hy'},

{'kind': 'drink', 'category': 'Beer', 'name': 'Stella', 'quantity': '1 շիշ', 'price': 1000, 'description': 'Stella, շատ լավ Stella, հոյակապ Stella', 'image': 'test_beer_stella.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Bud', 'quantity': '1 շիշ', 'price': 1100, 'description': 'Bud, շատ լավ Bud, հոյակապ Bud', 'image': 'test_bud_beer.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Heineken', 'quantity': '1 շիշ', 'price': 1500, 'description': 'Heineken, շատ լավ Heineken, հոյակապ Heineken', 'image': 'test_heineken_beer.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Corona', 'quantity': '1 շիշ', 'price': 800, 'description': 'Corona, շատ լավ Corona, հոյակապ Corona', 'image': 'test_corona_beer.webp', 'language': 'hy'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Tuborg', 'quantity': '1 շիշ', 'price': 1100, 'description': 'Tuborg, շատ լավ Tuborg, հոյակապ Tuborg', 'image': 'test_tuborg_beer.webp', 'language': 'hy'},


# dessert
# Cake
{'kind': 'dessert', 'category': 'Cake', 'name': 'Բրաունի', 'quantity': '1 կտոր', 'price': 800, 'description': 'Համալրված, լկված և լիարժեք պատրաստված, այս բրաունի առաջարկում է համեղ շոկոլադի համ, որը հալում է բերանում ամեն կերակուրից հետո։ Աληшին դասական համը սիրահարների համար։', 'image': 'test_dessert_brownie.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Հրեշտակ', 'quantity': '1 կտոր', 'price': 550, 'description': 'Թեթև և փափուկ տորթ, որը յուրաքանչյուր կերակուրից հետո զգացվում է որպես երկնքի պես։ Այս նուրբ համը հալվում է բերանում՝ թողնելով քաղցր և նուրբ համ։ Իրական հրեշտակային դեսերտ։', 'image': 'test_angel_cake.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Բլեքաութ', 'quantity': '1 կտոր', 'price': 650, 'description': 'Հագեցած, մուգ տորթ՝ ինտենսիվ համերի շերտերով։ Իդեալականորեն հավասարակշռված շոկոլադի խորը համով, Բլեքաութ տորթը առաջարկում է բավարար փորձ, որը թողնում է համեղ ցանկություն։', 'image': 'test_blackout_cake.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Բաթենբերգ', 'quantity': '1 կտոր', 'price': 400, 'description': 'Traditional բրիտանական տորթ, գեղեցիկ շերտավորված մնդի և մրգի համերով։ Բաթենբերգ տորթը առաջարկում է հաճելի հավասարակշռություն հյուսվածքների և համերի մեջ, դարձնելով յուրաքանչյուր խմորը իսկական հաճույք։', 'image': 'test_battenberg_cake.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Բանդտ', 'quantity': '1 կտոր', 'price': 800, 'description': 'Համեղ ու խոնավ Բանդտ տորթ, հարուստ համով և գեղեցիկ ներկայացմամբ։ Ցանկացած առիթի համար իդեալական, այս տորթը կتركե ձեզ հաճելի զգացողություն։', 'image': 'test_bundt_cake.webp', 'language': 'hy'},

# Icecream
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Ջելատո', 'quantity': '1 կտոր', 'price': 800, 'description': 'Ջելատո՝ սահուն և կրեմաձև սառեցված դեսերտ, հարուստ համով, իդեալական սառցաբույր սիրահարների համար։ Անկրկնելի փորձ յուրաքանչյուր կտորում։', 'image': 'test_icecream_chocolategelato.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Մանգո Կուլֆի', 'quantity': '1 կտոր', 'price': 650, 'description': 'Մանգո Կուլֆի՝ հարուստ և կրեմային սառեցված դեսերտ, որը ունի մանգոյի վառ համ, առաջարկելով թարմացնող և հաճելի համտես:', 'image': 'test_mangokulfi_icecream.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Ֆիլադելֆիա', 'quantity': '1 կտոր', 'price': 700, 'description': 'Ֆիլադելֆիա՝ կրեմային և հարուստ սառեցված դեսերտ, որը մատուցում է հարթ և հաճելի համ՝ թթվայնությամբ և քաղցրությամբ համեմված:', 'image': 'test_philadelphia_icecream.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Իտալական սառույց', 'quantity': '1 կտոր', 'price': 600, 'description': 'Իտալական սառույց՝ թարմացնող սառեցված treat, որն առաջարկում է թթու և պտղային համ, որը կատարյալ է տաք օրվա համար:', 'image': 'test_italianice_icecream.webp', 'language': 'hy'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Պոպսիկլ', 'quantity': '1 կտոր', 'price': 800, 'description': 'Պոպսիկլ՝ համեղ սառեցված treat, որն առաջարկում է թարմացնող համ՝ յուրաքանչյուր կտորով:', 'image': 'test_popsicle_icecream.webp', 'language': 'hy'},



# salad
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Մեծ իտալական աղցան', 'quantity': '1 ափսե', 'price': 1200, 'description': 'Իտալական աղցան, շատ լավ Իտալական աղցան, հոյակապ Իտալական աղցան', 'image': 'test_salad_bigitaliansalad.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Ցեզար աղցան', 'quantity': '1 ափսե', 'price': 1500, 'description': 'Դասական Ցեզար աղցան խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_caesar_green.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Այգու աղցան', 'quantity': '1 ափսե', 'price': 1600, 'description': 'Դասական Այգու աղցան խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_garden_green.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Միչիգանի աղցան', 'quantity': '1 ափսե', 'price': 2300, 'description': 'Միչիգանի աղցան խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_michigan_green.webp', 'language': 'hy'},

{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Կոբ', 'quantity': '1 բաժին', 'price': 2800, 'description': 'Կոբ խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_cobb_vegetable.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Ակար', 'quantity': '1 բաժին', 'price': 1800, 'description': 'Ակար խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_acarvegetable.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Մորթու տակ հելինգ', 'quantity': '1 բաժին', 'price': 1900, 'description': 'Մորթու տակ հելինգ խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_dressedherring_vegetable.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Ավգան', 'quantity': '1 բաժին', 'price': 2000, 'description': 'Ավգան խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_ahfgan_vegetable.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Սելերի Վիկտոր', 'quantity': '1 բաժին', 'price': 2100, 'description': 'Սելերի Վիկտոր խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_celeryvictor_vegetable.webp', 'language': 'hy'},

{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Մակեդոնիա', 'quantity': '1 բաժին', 'price': 2400, 'description': 'Մակեդոնիա խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_macadonia_fruit.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Ամբրոզիա', 'quantity': '1 բաժին', 'price': 2400, 'description': 'Ամբրոզիա խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_ambrosia_fruit.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Տամ ֆոնլամայ ռուամ', 'quantity': '1 բաժին', 'price': 2000, 'description': 'Տամ ֆոնլամայ ռուամ խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_tamphonlamai_fruit.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Բանան', 'quantity': '1 բաժին', 'price': 1100, 'description': 'Բանան խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_banana_fruit.webp', 'language': 'hy'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Ժելե', 'quantity': '1 բաժին', 'price': 1750, 'description': 'Ժելե խրթխրթան հազարով, պարմեզանով, չորահացով և սերուցքային սոուսով։', 'image': 'test_jello_fruit.webp', 'language': 'hy'},

]