datalist_ru = [

# food
{'kind': 'food', 'category': 'Pizza', 'name': 'Пицца Пепперони', 'quantity': '1 кусок', 'price': 450, 'description': 'Пицца Пепперони — классический фаворит с насыщенным, пикантным вкусом. Основа из мягкого, запечённого теста покрыта томатным соусом, расплавленным сыром моцарелла и ломтиками острой пепперони. Каждый укус дополняется смесью итальянских трав, таких как орегано и базилик. Завершается лёгкой струйкой оливкового масла, придающей пицце хрустящую и ароматную нотку.', 'image': 'test_pizza_pepperoni.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Pizza', 'name': 'Пицца Маргарита', 'quantity': '1 кусок', 'price': 300, 'description': 'Пицца Маргарита — это простая, но восхитительная классика. Она состоит из тонкого, хрустящего теста, покрытого свежим томатным соусом, кремообразным моцареллой и посыпанного ароматными листьями базилика. Пицца завершается каплей оливкового масла, которое подчеркивает свежие, легкие и гармоничные вкусы ингредиентов. Это идеальный выбор для тех, кто ценит традиционные итальянские ароматы.', 'image': 'test_pizza_margarita.webp', 'language': 'ru'},
{"kind": "food", "category": "Pizza", "name": "Пицца Капричоза", "quantity": "1 кусок", "price": 650, "description": "Пицца Капричоза — это насыщенный и ароматный выбор для любителей пиццы. Она состоит из хрустящего теста, покрытого богатым томатным соусом, кремообразной моцареллой, вкусным ветчиной, грибами и артишоками. Пицца завершается посыпкой оливок и каплей оливкового масла, что придает ей сбалансированное сочетание соленых и кисловатых вкусов. Это идеальный выбор для тех, кто любит разнообразие текстур и вкусов в одном укусе.", "image": "test_pizza_capricciosa.webp", "language": "ru"},
{'kind': 'food', 'category': 'Pizza', 'name': 'Пицца с грибами', 'quantity': '1 кусок', 'price': 500, 'description': 'Пицца с грибами — это замечательный выбор для любителей грибов. Пицца покрыта богатым томатным соусом, кремовой моцареллой и щедрой порцией свежих грибов. Землистый вкус грибов идеально сочетается с кремовым сыром и соленым соусом, создавая идеальный баланс текстур и вкусов. Эта пицца — отличный выбор для тех, кто ценит глубокие вкусы грибов на хрустящей корочке.', 'image': 'test_pizza_mushroom.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Pizza', 'name': 'Пицца с морепродуктами', 'quantity': '1 кусок', 'price': 700, 'description': 'Пицца с морепродуктами — идеальный выбор для любителей морепродуктов. Эта пицца содержит прекрасное сочетание креветок, кальмаров и мидий, покрытых богатым томатным соусом и расплавленной моцареллой. Соленые морепродукты прекрасно сочетаются с кремовым сыром, создавая гармонию вкусов. Наслаждайтесь вкусом океана с каждым кусочком этой ароматной пиццы.', 'image': 'test_pizza_seafood.webp', 'language': 'ru'},

{'kind': 'food', 'category': 'Soup', 'name': 'Томатный суп', 'quantity': '1 тарелка', 'price': 1800, 'description': 'Томатный суп — это классика, которая подарит вам комфорт в любое время года. Этот насыщенный и кремовый суп приготовлен из свежих помидоров, медленно вареных с ароматными травами и специями. Гладкая текстура и насыщенный вкус согреют вас изнутри. Наслаждайтесь вкусом домашнего супа, настоящим наслаждением для ваших вкусовых рецепторов.', 'image': 'test_tomato_soup.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Soup', 'name': 'Куриный суп с лапшой', 'quantity': '1 тарелка', 'price': 2400, 'description': 'Куриный суп с лапшой — это сытное и ароматное блюдо, приготовленное с нежными кусочками курицы, насыщенным бульоном и мягкой лапшой. Комбинация свежих овощей и ароматных специй создает комфортный и питательный суп. Идеален для любого времени года, этот суп согреет вас и утолит голод своим вкусом.', 'image': 'test_chicken_noodle_soup.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Soup', 'name': 'Суп с брокколи и чеддером', 'quantity': '1 тарелка', 'price': 2200, 'description': 'Суп с брокколи и чеддером — это кремовый и вкусный суп, приготовленный с свежим брокколи и расплавленным чеддером. Богатая, бархатистая текстура в сочетании с земляным вкусом брокколи и резкостью чеддера делает этот суп не только уютным, но и сытным. Идеален для уютного обеда, этот суп подарит вам теплое и насыщенное впечатление.', 'image': 'test_borccoli_cheddar_soup.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Soup', 'name': 'Суп с клецками мацо', 'quantity': '1 тарелка', 'price': 2500, 'description': 'Суп с клецками мацо — это уютный, пикантный суп, приготовленный с легкими и воздушными клецками мацо, поданными в ароматном курином бульоне. Клецки мацо, сделанные из мацового мучного, яиц и приправ, имеют приятную текстуру, а насыщенный бульон придает блюду тепло и глубину вкуса. Классическое еврейское комфортное блюдо, идеально подходящее для любого повода.', 'image': 'test_matzo_ball_soup.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Soup', 'name': 'Фо суп', 'quantity': '1 тарелка', 'price': 2100, 'description': 'Суп Фо — традиционное вьетнамское блюдо, включающее ароматный бульон, приготовленный из вареных говяжьих костей, трав и специй. Блюдо включает рисовую лапшу, тонко нарезанную говядину и свежие травы, предлагая богатый и пикантный вкус. Это идеальный выбор для теплого, сытного обеда, который одновременно утешает и насыщает вкусом.', 'image': 'test_pho_soup.avif', 'language': 'ru'},

{'kind': 'food', 'category': 'Barbecue', 'name': 'Свиныe рёбрышки', 'quantity': '1 порция', 'price': 3200, 'description': 'Нежные и сочные свиные рёбрышки, медленно приготовленные до совершенства с насыщенным дымным вкусом. Рёбрышки приправлены специальной смесью специй и барбекю-соусом, предлагая восхитительное сочетание солёных, сладких и дымных нот. Обязательное блюдо для любителей барбекю!', 'image': 'test_porkribs_barbecue.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Грудинка', 'quantity': '1 порция', 'price': 3200, 'description': 'Сочная и нежная грудинка, медленно приготовленная до совершенства с дымным вкусом. Она приправлена уникальной смесью специй и барбекю-соусом, предлагая солёный и насыщенный вкус, который тает во рту. Идеально для любителей барбекю, ищущих сытное и ароматное блюдо!', 'image': 'test_brisket_barbecue.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Целая свинья', 'quantity': '1 порция', 'price': 130000, 'description': 'Целая свинина, медленно приготовленная до совершенства с дымным вкусом и сочной нежностью. Этот грандиозный опыт барбекю приправлен смесью специй и готовится медленно, чтобы каждый кусочек был полон насыщенного дымного вкуса. Идеально для крупных собраний или тех, кто ищет незабываемое угощение!', 'image': 'test_wholehog_barbecue.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Курица', 'quantity': '1 порция', 'price': 2800, 'description': 'Нежная курица, идеально приготовленная на гриле с дымным вкусом. Эта курица барбекю приправлена специальной смесью специй и готовится медленно для достижения идеального баланса сочности и дымности. Отличный выбор для любителей барбекю!', 'image': 'test_chicken_barbecue.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Barbecue', 'name': 'Кебаб', 'quantity': '1 порция', 'price': 1900, 'description': 'Вкусный и нежный шашлык, приготовленный на гриле, приправленный специальной смесью специй для незабываемого барбекю-опыта. Идеально приготовлен, чтобы раскрыть природные ароматы, и подается горячим для вкусного блюда!', 'image': 'test_qabab_barbecue.webp', 'language': 'ru'},

{'kind': 'food', 'category': 'Burger', 'name': 'Чизбургер', 'quantity': '1 порция', 'price': 1800, 'description': 'Классический чизбургер с сочной говяжьей котлетой, расплавленным сыром и свежими ингредиентами, подается в мягкой булочке для удовлетворяющего и вкусного блюда. Отлично подходит для любителей бургеров, которые ценят прекрасное сочетание вкусов!', 'image': 'test_cheeseburger_burger.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Burger', 'name': 'Бекон бургер', 'quantity': '1 порция', 'price': 2200, 'description': 'Вкусный бекон бургер с сочной говяжьей котлетой, хрустящим беконом, расплавленным сыром и свежими ингредиентами, подается в мягкой булочке для аппетитного блюда. Отлично подходит для любителей бекона, которые наслаждаются насыщенным и вкусным вкусом!', 'image': 'test_baconburger_burger.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Burger', 'name': 'Куриный бургер', 'quantity': '1 порция', 'price': 2000, 'description': 'Вкусный куриный бургер с нежной куриной котлетой, свежими овощами и мягкой булочкой, который подарит удовлетворение и насыщенный вкус тем, кто предпочитает курицу вместо говядины. Идеальное сочетание вкуса и текстуры для любителей бургеров.', 'image': 'test_chickenburger_burger.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Burger', 'name': 'Бургер для завтрака', 'quantity': '1 порция', 'price': 2400, 'description': 'Начните свой день с вкусного завтрака-бургера, который сочетает в себе яйца, бекон, сыр и мягкую булочку. Этот сытный завтрак идеально подходит для тех, кто хочет сытно и вкусно начать утро.', 'image': 'test_breakfastburger_burger.webp', 'language': 'ru'},
{'kind': 'food', 'category': 'Burger', 'name': 'Веган слайдеры', 'quantity': '1 порция', 'price': 2500, 'description': 'Наслаждайтесь растительным удовольствием с этими веганскими слайдерами. Каждый слайдер содержит вкусную котлету, свежие овощи и мягкую булочку, предлагая вкусный и сытный укус для веганов и не только.', 'image': 'test_sliders_burger.webp', 'language': 'ru'},


# drink
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Лонг-Айленд', 'quantity': '1 бокал', 'price': 3400, 'description': 'Лонг-Айленд, очень хороший Лонг-Айленд, отличный Лонг-Айленд', 'image': 'test_cocktail_longisland.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Блади Мария', 'quantity': '1 бокал', 'price': 4200, 'description': 'Блади Мария, очень хорошая Блади Мария, отличная Блади Мария', 'image': 'test_bloodymaria_cocktail.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Мохито', 'quantity': '1 бокал', 'price': 1800, 'description': 'Мохито, очень хороший Мохито, отличный Мохито', 'image': 'test_mojito_cocktail.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Негрони', 'quantity': '1 бокал', 'price': 2200, 'description': 'Негрони, очень хороший Негрони, отличный Негрони', 'image': 'test_nogroni_cocktail.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Cocktail', 'name': 'Манхэттен', 'quantity': '1 бокал', 'price': 2800, 'description': 'Манхэттен, очень хороший Манхэттен, отличный Манхэттен', 'image': 'test_manhattan_cocktail.webp', 'language': 'ru'},

{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Кока-Кола', 'quantity': '1 бутылка', 'price': 550, 'description': 'Кока-Кола, очень хорошая Кока-Кола, отличная Кока-Кола', 'image': 'test_sodadrink_cocacola.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Фанта', 'quantity': '1 бутылка', 'price': 550, 'description': 'Фанта, очень хорошая Фанта, отличная Фанта', 'image': 'test_fanta_sodadrink.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Спрайт', 'quantity': '1 бутылка', 'price': 550, 'description': 'Спрайт, очень хороший Спрайт, отличный Спрайт', 'image': 'test_sprite_sodadrink.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Пепси', 'quantity': '1 бутылка', 'price': 550, 'description': 'Пепси, очень хорошая Пепси, отличная Пепси', 'image': 'test_pepsi_sodadrink.avif', 'language': 'ru'},
{'kind': 'drink', 'category': 'SodaDrink', 'name': 'Миринда', 'quantity': '1 бутылка', 'price': 550, 'description': 'Миринда, очень хорошая Миринда, отличная Миринда', 'image': 'test_mirinda_sodadrink.webp', 'language': 'ru'},

{'kind': 'drink', 'category': 'Vodka', 'name': 'Абсолют', 'quantity': '1 бутылка', 'price': 13500, 'description': 'Абсолют, очень хороший Абсолют, отличный Абсолют', 'image': 'test_vodka_absolut.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Финляндия', 'quantity': '1 бутылка', 'price': 9000, 'description': 'Финляндия, очень хорошая Финляндия, отличная Финляндия', 'image': 'test_finlandia_vodka.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Русский Стандарт', 'quantity': '1 бутылка', 'price': 12000, 'description': 'Русский Стандарт, очень хороший Русский Стандарт, отличный Русский Стандарт', 'image': 'test_russianstandard_vodka.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'Столичная', 'quantity': '1 бутылка', 'price': 11500, 'description': 'Столичная, очень хорошая Столичная, отличная Столичная', 'image': 'test_stolichnaya_vodka.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Vodka', 'name': 'СКАЙ', 'quantity': '1 бутылка', 'price': 13000, 'description': 'СКАЙ, очень хороший СКАЙ, отличный СКАЙ', 'image': 'test_skyy_vodka.webp', 'language': 'ru'},

{'kind': 'drink', 'category': 'Beer', 'name': 'Стелла', 'quantity': '1 бутылка', 'price': 1000, 'description': 'Стелла, очень хорошая Стелла, отличная Стелла', 'image': 'test_beer_stella.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Буд', 'quantity': '1 бутылка', 'price': 1100, 'description': 'Буд, очень хороший Буд, отличный Буд', 'image': 'test_bud_beer.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Хайнекен', 'quantity': '1 бутылка', 'price': 1500, 'description': 'Хайнекен, очень хороший Хайнекен, отличный Хайнекен', 'image': 'test_heineken_beer.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Корона', 'quantity': '1 бутылка', 'price': 800, 'description': 'Корона, очень хорошая Корона, отличная Корона', 'image': 'test_corona_beer.webp', 'language': 'ru'},
{'kind': 'drink', 'category': 'Beer', 'name': 'Туборг', 'quantity': '1 бутылка', 'price': 1100, 'description': 'Туборг, очень хороший Туборг, отличный Туборг', 'image': 'test_tuborg_beer.webp', 'language': 'ru'},


# dessert
# Cake
{'kind': 'dessert', 'category': 'Cake', 'name': 'Брауни', 'quantity': '1 кусок', 'price': 800, 'description': 'Богатый, насыщенный и идеально приготовленный, этот брауни предлагает восхитительный шоколадный вкус, который тает во рту с каждым кусочком. Настоящая классика для любителей десертов.', 'image': 'test_dessert_brownie.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Ангел', 'quantity': '1 кусок', 'price': 550, 'description': 'Легкий и воздушный торт, который ощущается как рай с каждым кусочком. Этот нежный десерт тает во рту, оставляя сладкий и мягкий послевкусие. Настоящий ангельский десерт.', 'image': 'test_angel_cake.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Блэкаут', 'quantity': '1 кусок', 'price': 650, 'description': 'Насыщенный, темный торт с слоями интенсивного вкуса. Идеально сбалансированный с роскошным шоколадным вкусом, торт Блэкаут предлагает удовлетворяющий опыт, который оставляет вас жаждущими еще.', 'image': 'test_blackout_cake.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Баттенберг', 'quantity': '1 кусок', 'price': 400, 'description': 'Традиционный британский торт, красиво слоёный с миндальными и фруктовыми вкусами. Торт Баттенберг предлагает восхитительный баланс текстур и вкусов, делая каждый укус настоящим наслаждением.', 'image': 'test_battenberg_cake.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Cake', 'name': 'Бандт', 'quantity': '1 кусок', 'price': 800, 'description': 'Влажный и вкусный торт Бандт с насыщенным вкусом и красивым оформлением. Идеален для любого повода, этот торт оставит вас в восторге.', 'image': 'test_bundt_cake.webp', 'language': 'ru'},

# Icecream
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Джелато', 'quantity': '1 кусок', 'price': 800, 'description': 'Джелато — это гладкое и кремовое мороженое с насыщенным вкусом, идеальное для любителей мороженого. Приятное ощущение в каждом укусе.', 'image': 'test_icecream_chocolategelato.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Манго Кульфи', 'quantity': '1 кусок', 'price': 650, 'description': 'Манго Кульфи — это насыщенный и кремовый замороженный десерт с ярким вкусом манго, который подарит освежающее и вкусное наслаждение.', 'image': 'test_mangokulfi_icecream.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Филадельфия', 'quantity': '1 кусок', 'price': 700, 'description': 'Филадельфия — кремовое и насыщенное мороженое, предлагающее плавный и приятный вкус с кисловатым, но сладким оттенком.', 'image': 'test_philadelphia_icecream.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Итальянское мороженое', 'quantity': '1 кусок', 'price': 600, 'description': 'Итальянское мороженое, освежающее замороженное лакомство с кисловатым и фруктовым вкусом, идеально подходящее для жаркого дня.', 'image': 'test_italianice_icecream.webp', 'language': 'ru'},
{'kind': 'dessert', 'category': 'Icecream', 'name': 'Попсикл', 'quantity': '1 кусок', 'price': 800, 'description': 'Попсикл, очень вкусное замороженное лакомство, предлагающее освежающий вкус с каждым укусом.', 'image': 'test_popsicle_icecream.webp', 'language': 'ru'},



# salad
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Большой итальянский салат', 'quantity': '1 тарелка', 'price': 1200, 'description': 'Итальянский салат, очень хороший Итальянский салат, отличный Итальянский салат', 'image': 'test_salad_bigitaliansalad.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Цезарь салат', 'quantity': '1 тарелка', 'price': 1500, 'description': 'Классический Цезарь салат с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_caesar_green.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Садовый салат', 'quantity': '1 тарелка', 'price': 1600, 'description': 'Классический Садовый салат с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_garden_green.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'GreenSalad', 'name': 'Мичиганский салат', 'quantity': '1 тарелка', 'price': 2300, 'description': 'Мичиганский салат с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_michigan_green.webp', 'language': 'ru'},

{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Коб', 'quantity': '1 порция', 'price': 2800, 'description': 'Коб с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_cobb_vegetable.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Акар', 'quantity': '1 порция', 'price': 1800, 'description': 'Акар с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_acarvegetable.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Маринованный сельдь', 'quantity': '1 порция', 'price': 1900, 'description': 'Маринованный сельдь с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_dressedherring_vegetable.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Авган', 'quantity': '1 порция', 'price': 2000, 'description': 'Авган с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_ahfgan_vegetable.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'VegetableSalad', 'name': 'Сельдерей Виктор', 'quantity': '1 порция', 'price': 2100, 'description': 'Сельдерей Виктор с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_celeryvictor_vegetable.webp', 'language': 'ru'},

{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Македония', 'quantity': '1 порция', 'price': 2400, 'description': 'Македония с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_macadonia_fruit.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Амброзия', 'quantity': '1 порция', 'price': 2400, 'description': 'Амброзия с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_ambrosia_fruit.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Там фонламай рум', 'quantity': '1 порция', 'price': 2000, 'description': 'Там фонламай рум с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_tamphonlamai_fruit.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Банан', 'quantity': '1 порция', 'price': 1100, 'description': 'Банан с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_banana_fruit.webp', 'language': 'ru'},
{'kind': 'salad', 'category': 'FruitSalad', 'name': 'Желе', 'quantity': '1 порция', 'price': 1750, 'description': 'Желе с хрустящими крутонами, пармезаном, сухариками и сливочным соусом.', 'image': 'test_jello_fruit.webp', 'language': 'ru'},

]