"""add new table qr scan info to get and store info about the qr scans

Revision ID: 03b69753405f
Revises: df3dd39bb97f
Create Date: 2025-03-20 13:18:47.533631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b69753405f'
down_revision: Union[str, None] = 'df3dd39bb97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scan_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_scan_info_id'), 'qr_scan_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_scan_info_id'), table_name='qr_scan_info')
    op.drop_table('qr_scan_info')
    # ### end Alembic commands ###
