"""add new table reservations

Revision ID: 2133634831ab
Revises: 6ccddb8e099d
Create Date: 2025-05-22 15:42:47.013941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2133634831ab'
down_revision: Union[str, None] = '6ccddb8e099d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('reserve_date', sa.Date(), nullable=True),
    sa.Column('reserve_time', sa.Time(), nullable=True),
    sa.Column('guests_count', sa.Integer(), server_default='1', nullable=True),
    sa.Column('special_requests', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
