"""add new col to user idram tip payments -> horeka_part_paid (false or true) to know horeka part tips are paid or not yet

Revision ID: 264ac12abf37
Revises: 776ff738376d
Create Date: 2025-04-08 20:50:33.808415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264ac12abf37'
down_revision: Union[str, None] = '776ff738376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_idram_user_basic_tip', sa.Column('horeka_part_paid', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_idram_user_basic_tip', 'horeka_part_paid')
    # ### end Alembic commands ###
