"""add new pre_section col to terms

Revision ID: 46e0a4accc59
Revises: a6697d86560d
Create Date: 2025-05-28 16:51:28.330823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e0a4accc59'
down_revision: Union[str, None] = 'a6697d86560d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms_texts', sa.Column('pre_section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms_texts', 'pre_section')
    # ### end Alembic commands ###
