"""horeca_subs_plans

Revision ID: 5894b95dc35b
Revises: a2b6bd6a9201
Create Date: 2025-06-02 12:52:18.813233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5894b95dc35b'
down_revision: Union[str, None] = 'a2b6bd6a9201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horeca_subs_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), server_default='31', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horeca_subs_plans')
    # ### end Alembic commands ###
