"""add quantity column to horekamenu

Revision ID: 5d311be479fc
Revises: 135db04c479b
Create Date: 2025-02-13 13:52:05.490838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d311be479fc'
down_revision: Union[str, None] = '135db04c479b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horekamenu', sa.Column('quantity', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horekamenu', 'quantity')
    # ### end Alembic commands ###
