"""add new col to payments_idram_user_basic_tip horeka_part to know to user tip which part is horeka

Revision ID: 82d6099c38b7
Revises: d596984cf642
Create Date: 2025-03-31 17:09:45.931613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d6099c38b7'
down_revision: Union[str, None] = 'd596984cf642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments_idram_user_basic_tip', sa.Column('horeka_part', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments_idram_user_basic_tip', 'horeka_part')
    # ### end Alembic commands ###
