"""generate terms_text table

Revision ID: a2b6bd6a9201
Revises: 2133634831ab
Create Date: 2025-05-29 12:09:56.758826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b6bd6a9201'
down_revision: Union[str, None] = '2133634831ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_kind', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pre_section', sa.String(), nullable=True),
    sa.Column('sections', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_texts_id'), 'terms_texts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_texts_id'), table_name='terms_texts')
    op.drop_table('terms_texts')
    # ### end Alembic commands ###
