"""add new table to track users which wanna give a tip

Revision ID: b6664fee4b3b
Revises: 264ac12abf37
Create Date: 2025-04-17 18:13:31.146077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6664fee4b3b'
down_revision: Union[str, None] = '264ac12abf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_page_click_info_get',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.Column('horeka_tip_amount', sa.Float(), nullable=False),
    sa.Column('menu_tip_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_page_click_info_get_id'), 'tip_page_click_info_get', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_page_click_info_get_id'), table_name='tip_page_click_info_get')
    op.drop_table('tip_page_click_info_get')
    # ### end Alembic commands ###
