"""add new table to get info tip via idram end button click

Revision ID: bb7c500db569
Revises: b6664fee4b3b
Create Date: 2025-04-17 18:19:27.651193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7c500db569'
down_revision: Union[str, None] = 'b6664fee4b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_via_idram_end_button_info_get',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.Column('horeka_tip_amount', sa.Float(), nullable=False),
    sa.Column('menu_tip_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_via_idram_end_button_info_get_id'), 'tip_via_idram_end_button_info_get', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_via_idram_end_button_info_get_id'), table_name='tip_via_idram_end_button_info_get')
    op.drop_table('tip_via_idram_end_button_info_get')
    # ### end Alembic commands ###
