"""add new column to horeka clients table -> payment_amount to provide unique payment amount

Revision ID: c26907e9a17d
Revises: 03b69753405f
Create Date: 2025-03-20 18:05:44.688505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26907e9a17d'
down_revision: Union[str, None] = '03b69753405f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horekaclients', sa.Column('payment_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horekaclients', 'payment_amount')
    # ### end Alembic commands ###
