"""add new table horekaadmins and nullable=False in menu horekaclient_id

Revision ID: c274888374b7
Revises: e5be9580fd9a
Create Date: 2025-02-10 15:37:29.538001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c274888374b7'
down_revision: Union[str, None] = 'e5be9580fd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horekadmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horekaclient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horekaclient_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horekadmin')
    # ### end Alembic commands ###
