"""add new table payments_idram_user_basic_tip for user give a basic tip

Revision ID: d596984cf642
Revises: c26907e9a17d
Create Date: 2025-03-31 15:24:33.904264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd596984cf642'
down_revision: Union[str, None] = 'c26907e9a17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_idram_user_basic_tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.Column('payer_account', sa.String(), nullable=True),
    sa.Column('trans_id', sa.String(), nullable=True),
    sa.Column('trans_date', sa.String(), nullable=True),
    sa.Column('waiter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_payments_idram_user_basic_tip_id'), 'payments_idram_user_basic_tip', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idram_user_basic_tip_id'), table_name='payments_idram_user_basic_tip')
    op.drop_table('payments_idram_user_basic_tip')
    # ### end Alembic commands ###
