"""add user_feedbacks table

Revision ID: df3dd39bb97f
Revises: 915cc62acbbb
Create Date: 2025-03-19 15:18:19.210499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3dd39bb97f'
down_revision: Union[str, None] = '915cc62acbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horeka_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horeka_client_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
