"""add new table horekamenu to store the menues, in horekaclients table add created_at column

Revision ID: e5be9580fd9a
Revises: 5a28a60fe841
Create Date: 2025-02-10 15:13:13.488796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5be9580fd9a'
down_revision: Union[str, None] = '5a28a60fe841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horekamenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('preparation_time', sa.Time(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('horekaclient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horekaclient_id'], ['horekaclients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('horekaclients', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horekaclients', 'created_at')
    op.drop_table('horekamenu')
    # ### end Alembic commands ###
