"""add category column to menu

Revision ID: fb5adf632da8
Revises: 58475dae72c5
Create Date: 2025-03-01 18:01:22.901905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5adf632da8'
down_revision: Union[str, None] = '58475dae72c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horekamenu', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horekamenu', 'category')
    # ### end Alembic commands ###
